### ISSUE TITLE
Add the 24h format 

### ISSUE THREAD

**Issue by florent1933** [ryanburns23/paper-time-input#1]
It would be great, if you can add the 24h format. I lived in France and we don't use the 12h format.

Congratulation for all your web components, it's a great work!

**Comment by ryanburns23** [comment]
@florent1933 thank you for opening up this issue. 

I closed it and added a max-hour property, set that to 24 and you should be good to go.

**Comment by florent1933** [comment]
@ryanburns23 thanks for your quick work and reply.

**Comment by florent1933** [comment]
In the 24h format, we don't use amPm so you should add an option to hide AM and PM and return a value like "23:02" and not "23:02am"

**Comment by ryanburns23** [comment]
@florent1933  Okay, to solve this I kept it simple and replaced the `maxHour` property with `format`...
`format` defaults to 12, set this to 24 for the following:

- Leading zero added to hour
- AM/PM Dropdown hidden

I added a 24 hour section to the demo as well. Let me know if I missed anything.
Thanks!

**Comment by florent1933** [comment]
Nearly ready 👍 

One thing is missing : the name of the format is 24h, but the range of hours is 0-23. So 24:24 is invalid.

**Comment by ryanburns23** [comment]
@florent1933 okay I think I got everything
