### ISSUE TITLE
Setting minute to a value from 00-09 causes leading zero to be cut off

### ISSUE THREAD

**Issue by Hermanio** [ryanburns23/paper-time-input#5]
What it looks like:
![image](https://user-images.githubusercontent.com/8943361/29023730-9db28364-7b77-11e7-96e6-6374e20a3f99.png)
What it should look like:
![image](https://user-images.githubusercontent.com/8943361/29023759-b436e364-7b77-11e7-9701-f1a37cc07a6e.png)

**Comment by ryanburns23** [comment]
@Hermanio Thanks

Fixed in: 68f1a53
